export const ROUTE_LINKS = {
  home: '/',
  contact: '/contact',
  about: '/about',
  signup: '/signup',
  login: '/login',
  cart: '/cart',
  wishlist: '/wishlist',
  shop: '/shop',
  privacy: '/privacy',
  terms: '/terms',
  faq: '/faq',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  flashSaleProducts: '/products/flash-sales',
  bestSellingProducts: '/products/best-selling',
  allProducts: '/products/all',
  productDetails: (id: string) => `/products/details?id=${id}`,
};
export const ROUTES = [
  { href: ROUTE_LINKS.home, label: 'Home' },
  { href: ROUTE_LINKS.contact, label: 'Contact' },
  { href: ROUTE_LINKS.about, label: 'About' },
  { href: ROUTE_LINKS.signup, label: 'Sign Up' },
];
