import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { TopHeader } from '@/components/home/TopHeader';
import { MainHeader } from '@/components/home/MainHeader';
import { I18nProvider } from '@/components/providers/I18nProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  readonly children: React.ReactNode;
  readonly params: { locale: string };
}) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <I18nProvider>
          <TopHeader />
          <MainHeader />
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}
